// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewqmrgcephdlggwsgxpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cW1yZ2NlcGhkbGdnd3NneHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODc0NTAsImV4cCI6MjA2MDE2MzQ1MH0.w7HYUO5vs7F1I9pPEwbVX7Yj8PZ2HO0neiHVn_ipOpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);